services:
  postgres:
    image: postgres:16-alpine
    container_name: helpdesk-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: helpdesk
      POSTGRES_PASSWORD: helpdesk
      POSTGRES_DB: helpdesk
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: helpdesk-redis
    ports:
      - "6380:6379"

volumes:
  pgdata:
